spring.application.name=notification
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/notification_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin123
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

jwt.secret=aJcgl4t5POsiRKyfM0vUa0jvlOB9BNPhulkCRItBocm+tluXDKLchR6lwTWYr5bCy9UmlKW3rRo8HHIp

eureka.client.service-url.defaultZone=http://localhost:8090/eureka/
eureka.instance.prefer-ip-address=true
