spring.application.name=auth
server.port=9080

server.servlet.context-path=/api/v1

jwt.secret=aJcgl4t5POsiRKyfM0vUa0jvlOB9BNPhulkCRItBocm+tluXDKLchR6lwTWYr5bCy9UmlKW3rRo8HHIp
jwt.expiration=864000000

eureka.client.service-url.defaultZone=http://localhost:9090/eureka/
eureka.instance.prefer-ip-address=true