spring.application.name=auth
server.port=9080

jwt.secret=aJcgl4t5POsiRKyfM0vUa0jvlOB9BNPhulkCRItBocm+tluXDKLchR6lwTWYr5bCy9UmlKW3rRo8HHIp
jwt.expiration=864000000

eureka.client.service-url.defaultZone=http://ms-eureka-server:9090/eureka/
eureka.instance.prefer-ip-address=true