spring:
  datasource:
    url: jdbc:mysql://mysql:3306/reservation_db
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false

server:
  port: 9087

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-eureka-server:9090/eureka/
  instance:
    prefer-ip-address: true
